spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    dataSource:
      names: dcorder-00,dcorder-01,dcorder-02,dcorder-03
      dcorder-00:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/dcorder-00?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      dcorder-01:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/dcorder-01?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      dcorder-02:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/dcorder-02?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      dcorder-03:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/dcorder-03?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    sharding:
      default-data-source-name: dcorder-00
      tables:
        t_order:
          key-generator:
            column: user_id
            type: SNOWFLAKE
#          actual-data-nodes: dcorder-00.t_order_000$->{0..3},dcorder-01.t_order_000$->{4..7},dcorder-02.t_order_000$->{8..9},dcorder-02.t_order_00$->{10..11},dcorder-03.t_order_00$->{12..15}
          actual-data-nodes: dcorder-00.t_order_000$->{0..3},dcorder-01.t_order_000$->{4..7},dcorder-02.t_order_$->{(8..11).collect{t -> t.toString().padLeft(4,'0')}},dcorder-03.t_order_00$->{12..15}

          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: dcorder-$->{((user_id % 15).intdiv(4)).toString().padLeft(2,'0')}
          tableStrategy:
            inline:
              shardingColumn: user_id
              algorithm-expression: t_order_$->{(user_id % 15).toString().padLeft(4,'0')}
#          keyGeneratorColumnName: user_id
#          defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

mybatis:
  # model的包
  type-aliases-package:  com.snoweagle.dc.shadingjdbc.infra.dal.dataObject
  mapperLocations: classpath:dal/mapper/*.xml,classpath:dal/mapperExt/*.xml
  configuration:
    map-underscore-to-camel-case: true